# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/vanes/christmas/fpga_project/motor_interrupted/motor_interrupted.srcs/sources_1/bd/design_main/ip/design_main_auto_pc_0/design_main_auto_pc_0.xci
# IP: The module: 'design_main_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vanes/christmas/fpga_project/motor_interrupted/motor_interrupted.gen/sources_1/bd/design_main/ip/design_main_auto_pc_0/design_main_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_main_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/vanes/christmas/fpga_project/motor_interrupted/motor_interrupted.srcs/sources_1/bd/design_main/ip/design_main_auto_pc_0/design_main_auto_pc_0.xci
# IP: The module: 'design_main_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/vanes/christmas/fpga_project/motor_interrupted/motor_interrupted.gen/sources_1/bd/design_main/ip/design_main_auto_pc_0/design_main_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_main_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
