# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pines.xdc

# Block Designs: bd/design_main/design_main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main || ORIG_REF_NAME==design_main} -quiet] -quiet

# IP: bd/design_main/ip/design_main_processing_system7_0_0/design_main_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_processing_system7_0_0 || ORIG_REF_NAME==design_main_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_axi_gpio_0_0/design_main_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_axi_gpio_0_0 || ORIG_REF_NAME==design_main_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_axi_interconnect_0_0/design_main_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_axi_interconnect_0_0 || ORIG_REF_NAME==design_main_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_proc_sys_reset_0_0/design_main_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_proc_sys_reset_0_0 || ORIG_REF_NAME==design_main_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_main/ip/design_main_auto_pc_0/design_main_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_main_auto_pc_0 || ORIG_REF_NAME==design_main_auto_pc_0} -quiet] -quiet

# XDC: C:/Users/vanes/christmas/fpga_project/motor_interrupted/motor_interrupted.gen/sources_1/bd/design_main/design_main_ooc.xdc
